<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>default</name>
  <uuid>fd9c9dee-67a8-41b2-9fae-2387e9353226</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Rewards where
		the loyalty points is 0;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
