<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Compute total spend</name>
  <uuid>e62a3710-1ddb-47e0-a111-5d9827bc0a4c</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to a new Shopping cart where
   the total spend is the unit price * the quantity;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
